--
-- Data for Name: hcore_garea; Type: TABLE DATA; Schema: public; Owner: hydroscope
--

COPY hcore_garea (gentity_ptr_id, area) FROM stdin;
1	\N
2	\N
3	\N
4	\N
5	\N
6	\N
7	\N
8	\N
9	\N
10	\N
11	\N
12	\N
13	\N
14	\N
15	\N
16	\N
17	\N
18	\N
19	\N
20	\N
21	\N
22	\N
23	\N
24	\N
25	\N
26	\N
27	\N
28	\N
29	\N
30	\N
31	\N
32	\N
33	\N
34	\N
35	\N
36	\N
37	\N
38	\N
39	\N
40	\N
41	\N
42	\N
43	\N
44	\N
45	\N
46	\N
47	\N
48	\N
49	\N
50	\N
51	\N
52	\N
53	\N
54	\N
55	\N
56	\N
57	\N
58	\N
59	\N
60	\N
61	\N
62	\N
63	\N
64	\N
65	\N
66	\N
67	\N
68	\N
69	\N
70	\N
71	\N
72	\N
73	\N
74	\N
75	\N
76	\N
77	\N
78	\N
79	\N
80	\N
81	\N
82	\N
83	\N
84	\N
85	\N
86	\N
87	\N
88	\N
89	\N
90	\N
91	\N
92	\N
93	\N
94	\N
95	\N
96	\N
97	\N
98	\N
99	\N
100	\N
101	\N
102	\N
103	\N
104	\N
105	\N
106	\N
107	\N
108	\N
109	\N
110	\N
111	\N
112	\N
113	\N
114	\N
115	\N
116	\N
117	\N
118	\N
119	\N
120	\N
121	\N
122	\N
123	\N
124	\N
125	\N
126	\N
127	\N
128	\N
129	\N
130	\N
131	\N
132	\N
133	\N
134	\N
135	\N
136	\N
137	\N
138	\N
139	\N
140	\N
141	\N
142	\N
143	\N
144	\N
145	\N
146	\N
147	\N
148	\N
149	\N
150	\N
151	\N
152	\N
153	\N
154	\N
155	\N
156	\N
157	\N
158	\N
159	\N
160	\N
161	\N
162	\N
163	\N
164	\N
165	\N
166	\N
167	\N
168	\N
169	\N
170	\N
171	\N
172	\N
173	\N
174	\N
175	\N
176	\N
177	\N
178	\N
179	\N
180	\N
181	\N
182	\N
183	\N
184	\N
185	\N
186	\N
187	\N
188	\N
189	\N
190	\N
191	\N
192	\N
193	\N
194	\N
195	\N
196	\N
197	\N
198	\N
199	\N
200	\N
201	\N
202	\N
203	\N
204	\N
205	\N
206	\N
207	\N
208	\N
209	\N
210	\N
211	\N
212	\N
213	\N
214	\N
215	\N
216	\N
217	\N
218	\N
219	\N
220	\N
221	\N
222	\N
223	\N
224	\N
225	\N
226	\N
227	\N
228	\N
229	\N
230	\N
231	\N
232	\N
233	\N
234	\N
235	\N
236	\N
237	\N
238	\N
239	\N
240	\N
241	\N
242	\N
243	\N
244	\N
245	\N
246	\N
301	\N
302	\N
303	\N
304	\N
305	\N
306	\N
307	\N
308	\N
309	\N
310	\N
311	\N
312	\N
313	\N
406	\N
409	\N
410	\N
422	\N
414	\N
402	\N
426	\N
453	\N
454	\N
455	\N
456	\N
435	\N
444	\N
437	\N
407	\N
405	\N
448	\N
413	\N
430	\N
451	\N
420	\N
427	\N
419	\N
436	\N
418	\N
423	\N
445	\N
447	\N
428	\N
425	\N
408	\N
440	\N
411	\N
415	\N
452	\N
441	\N
446	\N
416	\N
412	\N
439	\N
429	\N
431	\N
421	\N
450	\N
438	\N
443	\N
434	\N
417	\N
403	\N
424	\N
404	\N
432	\N
449	\N
442	\N
511	\N
503	\N
507	\N
506	\N
502	\N
509	\N
501	\N
504	\N
505	\N
508	\N
512	\N
510	\N
513	\N
514	\N
\.


--
-- Data for Name: hcore_gentity; Type: TABLE DATA; Schema: public; Owner: hydroscope
--

COPY hcore_gentity (id, water_basin_id, water_division_id, political_division_id, name, short_name, remarks, name_alt, short_name_alt, remarks_alt, original_id, original_db_id, last_modified) FROM stdin;
1	\N	\N	\N	AFGHANISTAN	AFGHANISTAN		AFGHANISTAN	AFGHANISTAN		\N	\N	\N
2	\N	\N	\N	ÅLAND ISLANDS	ÅLAND ISLANDS		ÅLAND ISLANDS	ÅLAND ISLANDS		\N	\N	\N
3	\N	\N	\N	ALBANIA	ALBANIA		ALBANIA	ALBANIA		\N	\N	\N
4	\N	\N	\N	ALGERIA	ALGERIA		ALGERIA	ALGERIA		\N	\N	\N
5	\N	\N	\N	AMERICAN SAMOA	AMERICAN SAMOA		AMERICAN SAMOA	AMERICAN SAMOA		\N	\N	\N
6	\N	\N	\N	ANDORRA	ANDORRA		ANDORRA	ANDORRA		\N	\N	\N
7	\N	\N	\N	ANGOLA	ANGOLA		ANGOLA	ANGOLA		\N	\N	\N
8	\N	\N	\N	ANGUILLA	ANGUILLA		ANGUILLA	ANGUILLA		\N	\N	\N
9	\N	\N	\N	ANTARCTICA	ANTARCTICA		ANTARCTICA	ANTARCTICA		\N	\N	\N
10	\N	\N	\N	ANTIGUA AND BARBUDA	ANTIGUA AND BARBUDA		ANTIGUA AND BARBUDA	ANTIGUA AND BARBUDA		\N	\N	\N
11	\N	\N	\N	ARGENTINA	ARGENTINA		ARGENTINA	ARGENTINA		\N	\N	\N
12	\N	\N	\N	ARMENIA	ARMENIA		ARMENIA	ARMENIA		\N	\N	\N
13	\N	\N	\N	ARUBA	ARUBA		ARUBA	ARUBA		\N	\N	\N
14	\N	\N	\N	AUSTRALIA	AUSTRALIA		AUSTRALIA	AUSTRALIA		\N	\N	\N
15	\N	\N	\N	AUSTRIA	AUSTRIA		AUSTRIA	AUSTRIA		\N	\N	\N
16	\N	\N	\N	AZERBAIJAN	AZERBAIJAN		AZERBAIJAN	AZERBAIJAN		\N	\N	\N
17	\N	\N	\N	BAHAMAS	BAHAMAS		BAHAMAS	BAHAMAS		\N	\N	\N
18	\N	\N	\N	BAHRAIN	BAHRAIN		BAHRAIN	BAHRAIN		\N	\N	\N
19	\N	\N	\N	BANGLADESH	BANGLADESH		BANGLADESH	BANGLADESH		\N	\N	\N
20	\N	\N	\N	BARBADOS	BARBADOS		BARBADOS	BARBADOS		\N	\N	\N
21	\N	\N	\N	BELARUS	BELARUS		BELARUS	BELARUS		\N	\N	\N
22	\N	\N	\N	BELGIUM	BELGIUM		BELGIUM	BELGIUM		\N	\N	\N
23	\N	\N	\N	BELIZE	BELIZE		BELIZE	BELIZE		\N	\N	\N
24	\N	\N	\N	BENIN	BENIN		BENIN	BENIN		\N	\N	\N
25	\N	\N	\N	BERMUDA	BERMUDA		BERMUDA	BERMUDA		\N	\N	\N
26	\N	\N	\N	BHUTAN	BHUTAN		BHUTAN	BHUTAN		\N	\N	\N
27	\N	\N	\N	BOLIVIA, PLURINATIONAL STATE OF	BOLIVIA, PLURINATIONAL STATE OF		BOLIVIA, PLURINATIONAL STATE OF	BOLIVIA, PLURINATIONAL STATE OF		\N	\N	\N
28	\N	\N	\N	BOSNIA AND HERZEGOVINA	BOSNIA AND HERZEGOVINA		BOSNIA AND HERZEGOVINA	BOSNIA AND HERZEGOVINA		\N	\N	\N
29	\N	\N	\N	BOTSWANA	BOTSWANA		BOTSWANA	BOTSWANA		\N	\N	\N
30	\N	\N	\N	BOUVET ISLAND	BOUVET ISLAND		BOUVET ISLAND	BOUVET ISLAND		\N	\N	\N
31	\N	\N	\N	BRAZIL	BRAZIL		BRAZIL	BRAZIL		\N	\N	\N
32	\N	\N	\N	BRITISH INDIAN OCEAN TERRITORY	BRITISH INDIAN OCEAN TERRITORY		BRITISH INDIAN OCEAN TERRITORY	BRITISH INDIAN OCEAN TERRITORY		\N	\N	\N
33	\N	\N	\N	BRUNEI DARUSSALAM	BRUNEI DARUSSALAM		BRUNEI DARUSSALAM	BRUNEI DARUSSALAM		\N	\N	\N
34	\N	\N	\N	BULGARIA	BULGARIA		BULGARIA	BULGARIA		\N	\N	\N
35	\N	\N	\N	BURKINA FASO	BURKINA FASO		BURKINA FASO	BURKINA FASO		\N	\N	\N
36	\N	\N	\N	BURUNDI	BURUNDI		BURUNDI	BURUNDI		\N	\N	\N
37	\N	\N	\N	CAMBODIA	CAMBODIA		CAMBODIA	CAMBODIA		\N	\N	\N
38	\N	\N	\N	CAMEROON	CAMEROON		CAMEROON	CAMEROON		\N	\N	\N
39	\N	\N	\N	CANADA	CANADA		CANADA	CANADA		\N	\N	\N
40	\N	\N	\N	CAPE VERDE	CAPE VERDE		CAPE VERDE	CAPE VERDE		\N	\N	\N
41	\N	\N	\N	CAYMAN ISLANDS	CAYMAN ISLANDS		CAYMAN ISLANDS	CAYMAN ISLANDS		\N	\N	\N
42	\N	\N	\N	CENTRAL AFRICAN REPUBLIC	CENTRAL AFRICAN REPUBLIC		CENTRAL AFRICAN REPUBLIC	CENTRAL AFRICAN REPUBLIC		\N	\N	\N
43	\N	\N	\N	CHAD	CHAD		CHAD	CHAD		\N	\N	\N
44	\N	\N	\N	CHILE	CHILE		CHILE	CHILE		\N	\N	\N
45	\N	\N	\N	CHINA	CHINA		CHINA	CHINA		\N	\N	\N
46	\N	\N	\N	CHRISTMAS ISLAND	CHRISTMAS ISLAND		CHRISTMAS ISLAND	CHRISTMAS ISLAND		\N	\N	\N
47	\N	\N	\N	COCOS (KEELING) ISLANDS	COCOS (KEELING) ISLANDS		COCOS (KEELING) ISLANDS	COCOS (KEELING) ISLANDS		\N	\N	\N
48	\N	\N	\N	COLOMBIA	COLOMBIA		COLOMBIA	COLOMBIA		\N	\N	\N
49	\N	\N	\N	COMOROS	COMOROS		COMOROS	COMOROS		\N	\N	\N
50	\N	\N	\N	CONGO	CONGO		CONGO	CONGO		\N	\N	\N
51	\N	\N	\N	CONGO, THE DEMOCRATIC REPUBLIC OF THE	CONGO, THE DEMOCRATIC REPUBLIC OF THE		CONGO, THE DEMOCRATIC REPUBLIC OF THE	CONGO, THE DEMOCRATIC REPUBLIC OF THE		\N	\N	\N
52	\N	\N	\N	COOK ISLANDS	COOK ISLANDS		COOK ISLANDS	COOK ISLANDS		\N	\N	\N
53	\N	\N	\N	COSTA RICA	COSTA RICA		COSTA RICA	COSTA RICA		\N	\N	\N
54	\N	\N	\N	CÔTE D'IVOIRE	CÔTE D'IVOIRE		CÔTE D'IVOIRE	CÔTE D'IVOIRE		\N	\N	\N
55	\N	\N	\N	CROATIA	CROATIA		CROATIA	CROATIA		\N	\N	\N
56	\N	\N	\N	CUBA	CUBA		CUBA	CUBA		\N	\N	\N
57	\N	\N	\N	CYPRUS	CYPRUS		CYPRUS	CYPRUS		\N	\N	\N
58	\N	\N	\N	CZECH REPUBLIC	CZECH REPUBLIC		CZECH REPUBLIC	CZECH REPUBLIC		\N	\N	\N
59	\N	\N	\N	DENMARK	DENMARK		DENMARK	DENMARK		\N	\N	\N
60	\N	\N	\N	DJIBOUTI	DJIBOUTI		DJIBOUTI	DJIBOUTI		\N	\N	\N
61	\N	\N	\N	DOMINICA	DOMINICA		DOMINICA	DOMINICA		\N	\N	\N
62	\N	\N	\N	DOMINICAN REPUBLIC	DOMINICAN REPUBLIC		DOMINICAN REPUBLIC	DOMINICAN REPUBLIC		\N	\N	\N
63	\N	\N	\N	ECUADOR	ECUADOR		ECUADOR	ECUADOR		\N	\N	\N
64	\N	\N	\N	EGYPT	EGYPT		EGYPT	EGYPT		\N	\N	\N
65	\N	\N	\N	EL SALVADOR	EL SALVADOR		EL SALVADOR	EL SALVADOR		\N	\N	\N
66	\N	\N	\N	EQUATORIAL GUINEA	EQUATORIAL GUINEA		EQUATORIAL GUINEA	EQUATORIAL GUINEA		\N	\N	\N
67	\N	\N	\N	ERITREA	ERITREA		ERITREA	ERITREA		\N	\N	\N
68	\N	\N	\N	ESTONIA	ESTONIA		ESTONIA	ESTONIA		\N	\N	\N
69	\N	\N	\N	ETHIOPIA	ETHIOPIA		ETHIOPIA	ETHIOPIA		\N	\N	\N
70	\N	\N	\N	FALKLAND ISLANDS (MALVINAS)	FALKLAND ISLANDS (MALVINAS)		FALKLAND ISLANDS (MALVINAS)	FALKLAND ISLANDS (MALVINAS)		\N	\N	\N
71	\N	\N	\N	FAROE ISLANDS	FAROE ISLANDS		FAROE ISLANDS	FAROE ISLANDS		\N	\N	\N
72	\N	\N	\N	FIJI	FIJI		FIJI	FIJI		\N	\N	\N
73	\N	\N	\N	FINLAND	FINLAND		FINLAND	FINLAND		\N	\N	\N
74	\N	\N	\N	FRANCE	FRANCE		FRANCE	FRANCE		\N	\N	\N
75	\N	\N	\N	FRENCH GUIANA	FRENCH GUIANA		FRENCH GUIANA	FRENCH GUIANA		\N	\N	\N
76	\N	\N	\N	FRENCH POLYNESIA	FRENCH POLYNESIA		FRENCH POLYNESIA	FRENCH POLYNESIA		\N	\N	\N
77	\N	\N	\N	FRENCH SOUTHERN TERRITORIES	FRENCH SOUTHERN TERRITORIES		FRENCH SOUTHERN TERRITORIES	FRENCH SOUTHERN TERRITORIES		\N	\N	\N
78	\N	\N	\N	GABON	GABON		GABON	GABON		\N	\N	\N
79	\N	\N	\N	GAMBIA	GAMBIA		GAMBIA	GAMBIA		\N	\N	\N
80	\N	\N	\N	GEORGIA	GEORGIA		GEORGIA	GEORGIA		\N	\N	\N
81	\N	\N	\N	GERMANY	GERMANY		GERMANY	GERMANY		\N	\N	\N
82	\N	\N	\N	GHANA	GHANA		GHANA	GHANA		\N	\N	\N
83	\N	\N	\N	GIBRALTAR	GIBRALTAR		GIBRALTAR	GIBRALTAR		\N	\N	\N
84	\N	\N	\N	GREECE	GREECE		GREECE	GREECE		\N	\N	\N
85	\N	\N	\N	GREENLAND	GREENLAND		GREENLAND	GREENLAND		\N	\N	\N
86	\N	\N	\N	GRENADA	GRENADA		GRENADA	GRENADA		\N	\N	\N
87	\N	\N	\N	GUADELOUPE	GUADELOUPE		GUADELOUPE	GUADELOUPE		\N	\N	\N
88	\N	\N	\N	GUAM	GUAM		GUAM	GUAM		\N	\N	\N
89	\N	\N	\N	GUATEMALA	GUATEMALA		GUATEMALA	GUATEMALA		\N	\N	\N
90	\N	\N	\N	GUERNSEY	GUERNSEY		GUERNSEY	GUERNSEY		\N	\N	\N
91	\N	\N	\N	GUINEA	GUINEA		GUINEA	GUINEA		\N	\N	\N
92	\N	\N	\N	GUINEA-BISSAU	GUINEA-BISSAU		GUINEA-BISSAU	GUINEA-BISSAU		\N	\N	\N
93	\N	\N	\N	GUYANA	GUYANA		GUYANA	GUYANA		\N	\N	\N
94	\N	\N	\N	HAITI	HAITI		HAITI	HAITI		\N	\N	\N
95	\N	\N	\N	HEARD ISLAND AND MCDONALD ISLANDS	HEARD ISLAND AND MCDONALD ISLANDS		HEARD ISLAND AND MCDONALD ISLANDS	HEARD ISLAND AND MCDONALD ISLANDS		\N	\N	\N
96	\N	\N	\N	HOLY SEE (VATICAN CITY STATE)	HOLY SEE (VATICAN CITY STATE)		HOLY SEE (VATICAN CITY STATE)	HOLY SEE (VATICAN CITY STATE)		\N	\N	\N
97	\N	\N	\N	HONDURAS	HONDURAS		HONDURAS	HONDURAS		\N	\N	\N
98	\N	\N	\N	HONG KONG	HONG KONG		HONG KONG	HONG KONG		\N	\N	\N
99	\N	\N	\N	HUNGARY	HUNGARY		HUNGARY	HUNGARY		\N	\N	\N
100	\N	\N	\N	ICELAND	ICELAND		ICELAND	ICELAND		\N	\N	\N
101	\N	\N	\N	INDIA	INDIA		INDIA	INDIA		\N	\N	\N
102	\N	\N	\N	INDONESIA	INDONESIA		INDONESIA	INDONESIA		\N	\N	\N
103	\N	\N	\N	IRAN, ISLAMIC REPUBLIC OF	IRAN, ISLAMIC REPUBLIC OF		IRAN, ISLAMIC REPUBLIC OF	IRAN, ISLAMIC REPUBLIC OF		\N	\N	\N
104	\N	\N	\N	IRAQ	IRAQ		IRAQ	IRAQ		\N	\N	\N
105	\N	\N	\N	IRELAND	IRELAND		IRELAND	IRELAND		\N	\N	\N
106	\N	\N	\N	ISLE OF MAN	ISLE OF MAN		ISLE OF MAN	ISLE OF MAN		\N	\N	\N
107	\N	\N	\N	ISRAEL	ISRAEL		ISRAEL	ISRAEL		\N	\N	\N
108	\N	\N	\N	ITALY	ITALY		ITALY	ITALY		\N	\N	\N
109	\N	\N	\N	JAMAICA	JAMAICA		JAMAICA	JAMAICA		\N	\N	\N
110	\N	\N	\N	JAPAN	JAPAN		JAPAN	JAPAN		\N	\N	\N
111	\N	\N	\N	JERSEY	JERSEY		JERSEY	JERSEY		\N	\N	\N
112	\N	\N	\N	JORDAN	JORDAN		JORDAN	JORDAN		\N	\N	\N
113	\N	\N	\N	KAZAKHSTAN	KAZAKHSTAN		KAZAKHSTAN	KAZAKHSTAN		\N	\N	\N
114	\N	\N	\N	KENYA	KENYA		KENYA	KENYA		\N	\N	\N
115	\N	\N	\N	KIRIBATI	KIRIBATI		KIRIBATI	KIRIBATI		\N	\N	\N
116	\N	\N	\N	KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF	KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF		KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF	KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF		\N	\N	\N
117	\N	\N	\N	KOREA, REPUBLIC OF	KOREA, REPUBLIC OF		KOREA, REPUBLIC OF	KOREA, REPUBLIC OF		\N	\N	\N
118	\N	\N	\N	KUWAIT	KUWAIT		KUWAIT	KUWAIT		\N	\N	\N
119	\N	\N	\N	KYRGYZSTAN	KYRGYZSTAN		KYRGYZSTAN	KYRGYZSTAN		\N	\N	\N
120	\N	\N	\N	LAO PEOPLE'S DEMOCRATIC REPUBLIC	LAO PEOPLE'S DEMOCRATIC REPUBLIC		LAO PEOPLE'S DEMOCRATIC REPUBLIC	LAO PEOPLE'S DEMOCRATIC REPUBLIC		\N	\N	\N
121	\N	\N	\N	LATVIA	LATVIA		LATVIA	LATVIA		\N	\N	\N
122	\N	\N	\N	LEBANON	LEBANON		LEBANON	LEBANON		\N	\N	\N
123	\N	\N	\N	LESOTHO	LESOTHO		LESOTHO	LESOTHO		\N	\N	\N
124	\N	\N	\N	LIBERIA	LIBERIA		LIBERIA	LIBERIA		\N	\N	\N
125	\N	\N	\N	LIBYAN ARAB JAMAHIRIYA	LIBYAN ARAB JAMAHIRIYA		LIBYAN ARAB JAMAHIRIYA	LIBYAN ARAB JAMAHIRIYA		\N	\N	\N
126	\N	\N	\N	LIECHTENSTEIN	LIECHTENSTEIN		LIECHTENSTEIN	LIECHTENSTEIN		\N	\N	\N
127	\N	\N	\N	LITHUANIA	LITHUANIA		LITHUANIA	LITHUANIA		\N	\N	\N
128	\N	\N	\N	LUXEMBOURG	LUXEMBOURG		LUXEMBOURG	LUXEMBOURG		\N	\N	\N
129	\N	\N	\N	MACAO	MACAO		MACAO	MACAO		\N	\N	\N
130	\N	\N	\N	MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF	MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF		MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF	MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF		\N	\N	\N
131	\N	\N	\N	MADAGASCAR	MADAGASCAR		MADAGASCAR	MADAGASCAR		\N	\N	\N
132	\N	\N	\N	MALAWI	MALAWI		MALAWI	MALAWI		\N	\N	\N
133	\N	\N	\N	MALAYSIA	MALAYSIA		MALAYSIA	MALAYSIA		\N	\N	\N
134	\N	\N	\N	MALDIVES	MALDIVES		MALDIVES	MALDIVES		\N	\N	\N
135	\N	\N	\N	MALI	MALI		MALI	MALI		\N	\N	\N
136	\N	\N	\N	MALTA	MALTA		MALTA	MALTA		\N	\N	\N
137	\N	\N	\N	MARSHALL ISLANDS	MARSHALL ISLANDS		MARSHALL ISLANDS	MARSHALL ISLANDS		\N	\N	\N
138	\N	\N	\N	MARTINIQUE	MARTINIQUE		MARTINIQUE	MARTINIQUE		\N	\N	\N
139	\N	\N	\N	MAURITANIA	MAURITANIA		MAURITANIA	MAURITANIA		\N	\N	\N
140	\N	\N	\N	MAURITIUS	MAURITIUS		MAURITIUS	MAURITIUS		\N	\N	\N
141	\N	\N	\N	MAYOTTE	MAYOTTE		MAYOTTE	MAYOTTE		\N	\N	\N
142	\N	\N	\N	MEXICO	MEXICO		MEXICO	MEXICO		\N	\N	\N
143	\N	\N	\N	MICRONESIA, FEDERATED STATES OF	MICRONESIA, FEDERATED STATES OF		MICRONESIA, FEDERATED STATES OF	MICRONESIA, FEDERATED STATES OF		\N	\N	\N
144	\N	\N	\N	MOLDOVA, REPUBLIC OF	MOLDOVA, REPUBLIC OF		MOLDOVA, REPUBLIC OF	MOLDOVA, REPUBLIC OF		\N	\N	\N
145	\N	\N	\N	MONACO	MONACO		MONACO	MONACO		\N	\N	\N
146	\N	\N	\N	MONGOLIA	MONGOLIA		MONGOLIA	MONGOLIA		\N	\N	\N
147	\N	\N	\N	MONTENEGRO	MONTENEGRO		MONTENEGRO	MONTENEGRO		\N	\N	\N
148	\N	\N	\N	MONTSERRAT	MONTSERRAT		MONTSERRAT	MONTSERRAT		\N	\N	\N
149	\N	\N	\N	MOROCCO	MOROCCO		MOROCCO	MOROCCO		\N	\N	\N
150	\N	\N	\N	MOZAMBIQUE	MOZAMBIQUE		MOZAMBIQUE	MOZAMBIQUE		\N	\N	\N
151	\N	\N	\N	MYANMAR	MYANMAR		MYANMAR	MYANMAR		\N	\N	\N
152	\N	\N	\N	NAMIBIA	NAMIBIA		NAMIBIA	NAMIBIA		\N	\N	\N
153	\N	\N	\N	NAURU	NAURU		NAURU	NAURU		\N	\N	\N
154	\N	\N	\N	NEPAL	NEPAL		NEPAL	NEPAL		\N	\N	\N
155	\N	\N	\N	NETHERLANDS	NETHERLANDS		NETHERLANDS	NETHERLANDS		\N	\N	\N
156	\N	\N	\N	NETHERLANDS ANTILLES	NETHERLANDS ANTILLES		NETHERLANDS ANTILLES	NETHERLANDS ANTILLES		\N	\N	\N
157	\N	\N	\N	NEW CALEDONIA	NEW CALEDONIA		NEW CALEDONIA	NEW CALEDONIA		\N	\N	\N
158	\N	\N	\N	NEW ZEALAND	NEW ZEALAND		NEW ZEALAND	NEW ZEALAND		\N	\N	\N
159	\N	\N	\N	NICARAGUA	NICARAGUA		NICARAGUA	NICARAGUA		\N	\N	\N
160	\N	\N	\N	NIGER	NIGER		NIGER	NIGER		\N	\N	\N
161	\N	\N	\N	NIGERIA	NIGERIA		NIGERIA	NIGERIA		\N	\N	\N
162	\N	\N	\N	NIUE	NIUE		NIUE	NIUE		\N	\N	\N
163	\N	\N	\N	NORFOLK ISLAND	NORFOLK ISLAND		NORFOLK ISLAND	NORFOLK ISLAND		\N	\N	\N
164	\N	\N	\N	NORTHERN MARIANA ISLANDS	NORTHERN MARIANA ISLANDS		NORTHERN MARIANA ISLANDS	NORTHERN MARIANA ISLANDS		\N	\N	\N
165	\N	\N	\N	NORWAY	NORWAY		NORWAY	NORWAY		\N	\N	\N
166	\N	\N	\N	OMAN	OMAN		OMAN	OMAN		\N	\N	\N
167	\N	\N	\N	PAKISTAN	PAKISTAN		PAKISTAN	PAKISTAN		\N	\N	\N
168	\N	\N	\N	PALAU	PALAU		PALAU	PALAU		\N	\N	\N
169	\N	\N	\N	PALESTINIAN TERRITORY, OCCUPIED	PALESTINIAN TERRITORY, OCCUPIED		PALESTINIAN TERRITORY, OCCUPIED	PALESTINIAN TERRITORY, OCCUPIED		\N	\N	\N
170	\N	\N	\N	PANAMA	PANAMA		PANAMA	PANAMA		\N	\N	\N
171	\N	\N	\N	PAPUA NEW GUINEA	PAPUA NEW GUINEA		PAPUA NEW GUINEA	PAPUA NEW GUINEA		\N	\N	\N
172	\N	\N	\N	PARAGUAY	PARAGUAY		PARAGUAY	PARAGUAY		\N	\N	\N
173	\N	\N	\N	PERU	PERU		PERU	PERU		\N	\N	\N
174	\N	\N	\N	PHILIPPINES	PHILIPPINES		PHILIPPINES	PHILIPPINES		\N	\N	\N
175	\N	\N	\N	PITCAIRN	PITCAIRN		PITCAIRN	PITCAIRN		\N	\N	\N
176	\N	\N	\N	POLAND	POLAND		POLAND	POLAND		\N	\N	\N
177	\N	\N	\N	PORTUGAL	PORTUGAL		PORTUGAL	PORTUGAL		\N	\N	\N
178	\N	\N	\N	PUERTO RICO	PUERTO RICO		PUERTO RICO	PUERTO RICO		\N	\N	\N
179	\N	\N	\N	QATAR	QATAR		QATAR	QATAR		\N	\N	\N
180	\N	\N	\N	RÉUNION	RÉUNION		RÉUNION	RÉUNION		\N	\N	\N
181	\N	\N	\N	ROMANIA	ROMANIA		ROMANIA	ROMANIA		\N	\N	\N
182	\N	\N	\N	RUSSIAN FEDERATION	RUSSIAN FEDERATION		RUSSIAN FEDERATION	RUSSIAN FEDERATION		\N	\N	\N
183	\N	\N	\N	RWANDA	RWANDA		RWANDA	RWANDA		\N	\N	\N
184	\N	\N	\N	SAINT BARTHÉLEMY	SAINT BARTHÉLEMY		SAINT BARTHÉLEMY	SAINT BARTHÉLEMY		\N	\N	\N
185	\N	\N	\N	SAINT HELENA	SAINT HELENA		SAINT HELENA	SAINT HELENA		\N	\N	\N
186	\N	\N	\N	SAINT KITTS AND NEVIS	SAINT KITTS AND NEVIS		SAINT KITTS AND NEVIS	SAINT KITTS AND NEVIS		\N	\N	\N
187	\N	\N	\N	SAINT LUCIA	SAINT LUCIA		SAINT LUCIA	SAINT LUCIA		\N	\N	\N
188	\N	\N	\N	SAINT MARTIN	SAINT MARTIN		SAINT MARTIN	SAINT MARTIN		\N	\N	\N
189	\N	\N	\N	SAINT PIERRE AND MIQUELON	SAINT PIERRE AND MIQUELON		SAINT PIERRE AND MIQUELON	SAINT PIERRE AND MIQUELON		\N	\N	\N
190	\N	\N	\N	SAINT VINCENT AND THE GRENADINES	SAINT VINCENT AND THE GRENADINES		SAINT VINCENT AND THE GRENADINES	SAINT VINCENT AND THE GRENADINES		\N	\N	\N
191	\N	\N	\N	SAMOA	SAMOA		SAMOA	SAMOA		\N	\N	\N
192	\N	\N	\N	SAN MARINO	SAN MARINO		SAN MARINO	SAN MARINO		\N	\N	\N
193	\N	\N	\N	SAO TOME AND PRINCIPE	SAO TOME AND PRINCIPE		SAO TOME AND PRINCIPE	SAO TOME AND PRINCIPE		\N	\N	\N
194	\N	\N	\N	SAUDI ARABIA	SAUDI ARABIA		SAUDI ARABIA	SAUDI ARABIA		\N	\N	\N
195	\N	\N	\N	SENEGAL	SENEGAL		SENEGAL	SENEGAL		\N	\N	\N
196	\N	\N	\N	SERBIA	SERBIA		SERBIA	SERBIA		\N	\N	\N
197	\N	\N	\N	SEYCHELLES	SEYCHELLES		SEYCHELLES	SEYCHELLES		\N	\N	\N
198	\N	\N	\N	SIERRA LEONE	SIERRA LEONE		SIERRA LEONE	SIERRA LEONE		\N	\N	\N
199	\N	\N	\N	SINGAPORE	SINGAPORE		SINGAPORE	SINGAPORE		\N	\N	\N
200	\N	\N	\N	SLOVAKIA	SLOVAKIA		SLOVAKIA	SLOVAKIA		\N	\N	\N
201	\N	\N	\N	SLOVENIA	SLOVENIA		SLOVENIA	SLOVENIA		\N	\N	\N
202	\N	\N	\N	SOLOMON ISLANDS	SOLOMON ISLANDS		SOLOMON ISLANDS	SOLOMON ISLANDS		\N	\N	\N
203	\N	\N	\N	SOMALIA	SOMALIA		SOMALIA	SOMALIA		\N	\N	\N
204	\N	\N	\N	SOUTH AFRICA	SOUTH AFRICA		SOUTH AFRICA	SOUTH AFRICA		\N	\N	\N
205	\N	\N	\N	SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS	SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS		SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS	SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS		\N	\N	\N
206	\N	\N	\N	SPAIN	SPAIN		SPAIN	SPAIN		\N	\N	\N
207	\N	\N	\N	SRI LANKA	SRI LANKA		SRI LANKA	SRI LANKA		\N	\N	\N
208	\N	\N	\N	SUDAN	SUDAN		SUDAN	SUDAN		\N	\N	\N
209	\N	\N	\N	SURINAME	SURINAME		SURINAME	SURINAME		\N	\N	\N
210	\N	\N	\N	SVALBARD AND JAN MAYEN	SVALBARD AND JAN MAYEN		SVALBARD AND JAN MAYEN	SVALBARD AND JAN MAYEN		\N	\N	\N
211	\N	\N	\N	SWAZILAND	SWAZILAND		SWAZILAND	SWAZILAND		\N	\N	\N
212	\N	\N	\N	SWEDEN	SWEDEN		SWEDEN	SWEDEN		\N	\N	\N
213	\N	\N	\N	SWITZERLAND	SWITZERLAND		SWITZERLAND	SWITZERLAND		\N	\N	\N
214	\N	\N	\N	SYRIAN ARAB REPUBLIC	SYRIAN ARAB REPUBLIC		SYRIAN ARAB REPUBLIC	SYRIAN ARAB REPUBLIC		\N	\N	\N
215	\N	\N	\N	TAIWAN, PROVINCE OF CHINA	TAIWAN, PROVINCE OF CHINA		TAIWAN, PROVINCE OF CHINA	TAIWAN, PROVINCE OF CHINA		\N	\N	\N
216	\N	\N	\N	TAJIKISTAN	TAJIKISTAN		TAJIKISTAN	TAJIKISTAN		\N	\N	\N
217	\N	\N	\N	TANZANIA, UNITED REPUBLIC OF	TANZANIA, UNITED REPUBLIC OF		TANZANIA, UNITED REPUBLIC OF	TANZANIA, UNITED REPUBLIC OF		\N	\N	\N
218	\N	\N	\N	THAILAND	THAILAND		THAILAND	THAILAND		\N	\N	\N
219	\N	\N	\N	TIMOR-LESTE	TIMOR-LESTE		TIMOR-LESTE	TIMOR-LESTE		\N	\N	\N
220	\N	\N	\N	TOGO	TOGO		TOGO	TOGO		\N	\N	\N
221	\N	\N	\N	TOKELAU	TOKELAU		TOKELAU	TOKELAU		\N	\N	\N
222	\N	\N	\N	TONGA	TONGA		TONGA	TONGA		\N	\N	\N
223	\N	\N	\N	TRINIDAD AND TOBAGO	TRINIDAD AND TOBAGO		TRINIDAD AND TOBAGO	TRINIDAD AND TOBAGO		\N	\N	\N
224	\N	\N	\N	TUNISIA	TUNISIA		TUNISIA	TUNISIA		\N	\N	\N
225	\N	\N	\N	TURKEY	TURKEY		TURKEY	TURKEY		\N	\N	\N
226	\N	\N	\N	TURKMENISTAN	TURKMENISTAN		TURKMENISTAN	TURKMENISTAN		\N	\N	\N
227	\N	\N	\N	TURKS AND CAICOS ISLANDS	TURKS AND CAICOS ISLANDS		TURKS AND CAICOS ISLANDS	TURKS AND CAICOS ISLANDS		\N	\N	\N
228	\N	\N	\N	TUVALU	TUVALU		TUVALU	TUVALU		\N	\N	\N
229	\N	\N	\N	UGANDA	UGANDA		UGANDA	UGANDA		\N	\N	\N
230	\N	\N	\N	UKRAINE	UKRAINE		UKRAINE	UKRAINE		\N	\N	\N
231	\N	\N	\N	UNITED ARAB EMIRATES	UNITED ARAB EMIRATES		UNITED ARAB EMIRATES	UNITED ARAB EMIRATES		\N	\N	\N
232	\N	\N	\N	UNITED KINGDOM	UNITED KINGDOM		UNITED KINGDOM	UNITED KINGDOM		\N	\N	\N
233	\N	\N	\N	UNITED STATES	UNITED STATES		UNITED STATES	UNITED STATES		\N	\N	\N
234	\N	\N	\N	UNITED STATES MINOR OUTLYING ISLANDS	UNITED STATES MINOR OUTLYING ISLANDS		UNITED STATES MINOR OUTLYING ISLANDS	UNITED STATES MINOR OUTLYING ISLANDS		\N	\N	\N
235	\N	\N	\N	URUGUAY	URUGUAY		URUGUAY	URUGUAY		\N	\N	\N
236	\N	\N	\N	UZBEKISTAN	UZBEKISTAN		UZBEKISTAN	UZBEKISTAN		\N	\N	\N
237	\N	\N	\N	VANUATU	VANUATU		VANUATU	VANUATU		\N	\N	\N
238	\N	\N	\N	VENEZUELA, BOLIVARIAN REPUBLIC OF	VENEZUELA, BOLIVARIAN REPUBLIC OF		VENEZUELA, BOLIVARIAN REPUBLIC OF	VENEZUELA, BOLIVARIAN REPUBLIC OF		\N	\N	\N
239	\N	\N	\N	VIET NAM	VIET NAM		VIET NAM	VIET NAM		\N	\N	\N
240	\N	\N	\N	VIRGIN ISLANDS, BRITISH	VIRGIN ISLANDS, BRITISH		VIRGIN ISLANDS, BRITISH	VIRGIN ISLANDS, BRITISH		\N	\N	\N
241	\N	\N	\N	VIRGIN ISLANDS, U.S.	VIRGIN ISLANDS, U.S.		VIRGIN ISLANDS, U.S.	VIRGIN ISLANDS, U.S.		\N	\N	\N
242	\N	\N	\N	WALLIS AND FUTUNA	WALLIS AND FUTUNA		WALLIS AND FUTUNA	WALLIS AND FUTUNA		\N	\N	\N
243	\N	\N	\N	WESTERN SAHARA	WESTERN SAHARA		WESTERN SAHARA	WESTERN SAHARA		\N	\N	\N
244	\N	\N	\N	YEMEN	YEMEN		YEMEN	YEMEN		\N	\N	\N
245	\N	\N	\N	ZAMBIA	ZAMBIA		ZAMBIA	ZAMBIA		\N	\N	\N
246	\N	\N	\N	ZIMBABWE	ZIMBABWE		ZIMBABWE	ZIMBABWE		\N	\N	\N
301	\N	\N	\N	ΠΕΛΟΠΟΝΝΗΣΟΥ	ΠΕΛΟΠΟΝΝΗΣΟΥ					\N	\N	\N
302	\N	\N	\N	ΔΥΤΙΚΗΣ ΕΛΛΑΔΑΣ	ΔΥΤΙΚΗΣ ΕΛΛΑΔΑΣ					\N	\N	\N
303	\N	\N	\N	ΑΤΤΙΚΗΣ	ΑΤΤΙΚΗΣ					\N	\N	\N
304	\N	\N	\N	ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ	ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ					\N	\N	\N
305	\N	\N	\N	ΘΕΣΣΑΛΙΑΣ	ΘΕΣΣΑΛΙΑΣ					\N	\N	\N
306	\N	\N	\N	ΗΠΕΙΡΟΥ	ΗΠΕΙΡΟΥ					\N	\N	\N
307	\N	\N	\N	ΔΥΤΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ	ΔΥΤΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ					\N	\N	\N
308	\N	\N	\N	ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ	ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ					\N	\N	\N
309	\N	\N	\N	ΑΝΑΤΟΛΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ - ΘΡΑΚΗΣ	ΑΝΑΤΟΛΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ - ΘΡΑΚΗΣ					\N	\N	\N
310	\N	\N	\N	ΚΡΗΤΗΣ	ΚΡΗΤΗΣ					\N	\N	\N
311	\N	\N	\N	ΒΟΡΕΙΟΥ ΑΙΓΑΙΟΥ	ΒΟΡΕΙΟΥ ΑΙΓΑΙΟΥ					\N	\N	\N
312	\N	\N	\N	ΝΟΤΙΟΥ ΑΙΓΑΙΟΥ	ΝΟΤΙΟΥ ΑΙΓΑΙΟΥ					\N	\N	\N
313	\N	\N	\N	ΙΟΝΙΩΝ ΝΗΣΩΝ	ΙΟΝΙΩΝ ΝΗΣΩΝ					\N	\N	\N
406	\N	\N	\N	ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ    	ΑΙΤΩΛΟΑΚ					\N	\N	\N
409	\N	\N	\N	ΑΡΓΟΛΙΔΑΣ           	ΑΡΓΟΛΙΔΑ					\N	\N	\N
410	\N	\N	\N	ΑΡΚΑΔΙΑΣ            	ΑΡΚΑΔΙΑΣ					\N	\N	\N
422	\N	\N	\N	ΑΡΤΑΣ               	ΑΡΤΑΣ   					\N	\N	\N
414	\N	\N	\N	ΑΧΑΙΑΣ              	ΑΧΑΙΑΣ  					\N	\N	\N
402	\N	\N	\N	ΒΟΙΩΤΙΑΣ            	ΒΟΙΩΤΙΑΣ					\N	\N	\N
426	\N	\N	\N	ΓΡΕΒΕΝΩΝ            	ΓΡΕΒΕΝΩΝ					\N	\N	\N
453	\N	\N	\N	ΔΙΑΜ. ΑΘΗΝΑΣ        	ΑΘΗΝΑ   					\N	\N	\N
454	\N	\N	\N	ΔΙΑΜ. ΑΝΑΤ. ΑΤΤΙΚΗΣ 	Α-ΑΤΤΙΚΗ					\N	\N	\N
455	\N	\N	\N	ΔΙΑΜ. ΔΥΤ. ΑΤΤΙΚΗΣ  	Δ-ΑΤΤΙΚΗ					\N	\N	\N
456	\N	\N	\N	ΔΙΑΜ. ΠΕΙΡΑΙΑ       	ΠΕΙΡΑΙΑΣ					\N	\N	\N
435	\N	\N	\N	ΔΡΑΜΑΣ              	ΔΡΑΜΑΣ  					\N	\N	\N
444	\N	\N	\N	ΔΩΔΕΚΑΝΗΣΟΥ         	ΔΩΔΕΚΑΝ 					\N	\N	\N
437	\N	\N	\N	ΕΒΡΟΥ               	ΕΒΡΟΥ   					\N	\N	\N
407	\N	\N	\N	ΕΥΒΟΙΑΣ             	ΕΥΒΟΙΑΣ 					\N	\N	\N
405	\N	\N	\N	ΕΥΡΥΤΑΝΙΑΣ          	ΕΥΡΥΤΑΝ 					\N	\N	\N
448	\N	\N	\N	ΖΑΚΥΝΘΟΥ            	ΖΑΚΥΝΘΟΥ					\N	\N	\N
413	\N	\N	\N	ΗΛΕΙΑΣ              	ΗΛΕΙΑΣ  					\N	\N	\N
430	\N	\N	\N	ΗΜΑΘΙΑΣ             	ΗΜΑΘΙΑΣ 					\N	\N	\N
451	\N	\N	\N	ΗΡΑΚΛΕΙΟΥ           	ΗΡΑΚΛΕΙΟ					\N	\N	\N
420	\N	\N	\N	ΘΕΣΠΡΩΤΙΑΣ          	ΘΕΣΠΡΩΤ 					\N	\N	\N
427	\N	\N	\N	ΘΕΣΣΑΛΟΝΙΚΗΣ        	ΘΕΣΣΑΛΟΝ					\N	\N	\N
419	\N	\N	\N	ΙΩΑΝΝΙΝΩΝ           	ΙΩΑΝΝΙΝ 					\N	\N	\N
436	\N	\N	\N	ΚΑΒΑΛΑΣ             	ΚΑΒΑΛΑΣ 					\N	\N	\N
418	\N	\N	\N	ΚΑΡΔΙΤΣΑΣ           	ΚΑΡΔΙΤΣΑ					\N	\N	\N
423	\N	\N	\N	ΚΑΣΤΟΡΙΑΣ           	ΚΑΣΤΟΡΙΑ					\N	\N	\N
445	\N	\N	\N	ΚΕΡΚΥΡΑΣ            	ΚΕΡΚΥΡΑΣ					\N	\N	\N
447	\N	\N	\N	ΚΕΦΑΛΛΗΝΙΑΣ         	ΚΕΦΑΛΛΗΝ					\N	\N	\N
428	\N	\N	\N	ΚΙΛΚΙΣ              	ΚΙΛΚΙΣ  					\N	\N	\N
425	\N	\N	\N	ΚΟΖΑΝΗΣ             	ΚΟΖΑΝΗΣ 					\N	\N	\N
408	\N	\N	\N	ΚΟΡΙΝΘΙΑΣ           	ΚΟΡΙΝΘΙΑ					\N	\N	\N
440	\N	\N	\N	ΚΥΚΛΑΔΩΝ            	ΚΥΚΛΑΔΩΝ					\N	\N	\N
411	\N	\N	\N	ΛΑΚΩΝΙΑΣ            	ΛΑΚΩΝΙΑΣ					\N	\N	\N
415	\N	\N	\N	ΛΑΡΙΣΑΣ             	ΛΑΡΙΣΑΣ 					\N	\N	\N
452	\N	\N	\N	ΛΑΣΙΘΙΟΥ            	ΛΑΣΙΘΙΟΥ					\N	\N	\N
441	\N	\N	\N	ΛΕΣΒΟΥ              	ΛΕΣΒΟΥ  					\N	\N	\N
446	\N	\N	\N	ΛΕΥΚΑΔΑΣ            	ΛΕΥΚΑΔΑΣ					\N	\N	\N
416	\N	\N	\N	ΜΑΓΝΗΣΙΑΣ           	ΜΑΓΝΗΣΙΑ					\N	\N	\N
412	\N	\N	\N	ΜΕΣΣΗΝΙΑΣ           	ΜΕΣΣΗΝΙΑ					\N	\N	\N
439	\N	\N	\N	ΞΑΝΘΗΣ              	ΞΑΝΘΗΣ  					\N	\N	\N
429	\N	\N	\N	ΠΕΛΛΑΣ              	ΠΕΛΛΑΣ  					\N	\N	\N
431	\N	\N	\N	ΠΙΕΡΙΑΣ             	ΠΙΕΡΙΑΣ 					\N	\N	\N
421	\N	\N	\N	ΠΡΕΒΕΖΑΣ            	ΠΡΕΒΕΖΑΣ					\N	\N	\N
450	\N	\N	\N	ΡΕΘΥΜΝΟΥ            	ΡΕΘΥΜΝΟΥ					\N	\N	\N
438	\N	\N	\N	ΡΟΔΟΠΗΣ             	ΡΟΔΟΠΗΣ 					\N	\N	\N
443	\N	\N	\N	ΣΑΜΟΥ               	ΣΑΜΟΥ   					\N	\N	\N
434	\N	\N	\N	ΣΕΡΡΩΝ              	ΣΕΡΡΩΝ  					\N	\N	\N
417	\N	\N	\N	ΤΡΙΚΑΛΩΝ            	ΤΡΙΚΑΛΩΝ					\N	\N	\N
403	\N	\N	\N	ΦΘΙΩΤΙΔΑΣ           	ΦΘΙΩΤΙΔΑ					\N	\N	\N
424	\N	\N	\N	ΦΛΩΡΙΝΑΣ            	ΦΛΩΡΙΝΑΣ					\N	\N	\N
404	\N	\N	\N	ΦΩΚΙΔΑΣ             	ΦΩΚΙΔΑΣ 					\N	\N	\N
432	\N	\N	\N	ΧΑΛΚΙΔΙΚΗΣ          	ΧΑΛΚΙΔΙΚ					\N	\N	\N
449	\N	\N	\N	ΧΑΝΙΩΝ              	ΧΑΝΙΩΝ  					\N	\N	\N
442	\N	\N	\N	ΧΙΟΥ                	ΧΙΟΥ    					\N	\N	\N
511	\N	\N	\N	ΑΝΑΤΟΛΙΚΗ ΜΑΚΕΔΟΝΙΑ 	Α-ΜΑΚΕΔ 					\N	\N	\N
503	\N	\N	\N	ΑΝΑΤΟΛΙΚΗ ΠΕΛΟΠΟΝΝΗΣ	Α-ΠΕΛΟΠ 					\N	\N	\N
507	\N	\N	\N	ΑΝΑΤΟΛΙΚΗ ΣΤΕΡΕΑ ΕΛΛ	Α-ΣΤΕΡ  					\N	\N	\N
506	\N	\N	\N	ΑΤΤΙΚΗ              	ΑΤΤΙΚΗ  					\N	\N	\N
502	\N	\N	\N	ΒΟΡΕΙΑ ΠΕΛΟΠΟΝΝΗΣΟΣ 	Β-ΠΕΛΟΠ 					\N	\N	\N
509	\N	\N	\N	ΔΥΤΙΚΗ ΜΑΚΕΔΟΝΙΑ    	Δ-ΜΑΚΕΔ 					\N	\N	\N
501	\N	\N	\N	ΔΥΤΙΚΗ ΠΕΛΟΠΟΝΝΗΣΟΣ 	Δ-ΠΕΛΟΠ 					\N	\N	\N
504	\N	\N	\N	ΔΥΤΙΚΗ ΣΤΕΡΕΑ ΕΛΛΑΔΑ	Δ-ΣΤΕΡ  					\N	\N	\N
505	\N	\N	\N	ΗΠΕΙΡΟΣ             	ΗΠΕΙΡΟΣ 					\N	\N	\N
508	\N	\N	\N	ΘΕΣΣΑΛΙΑ            	ΘΕΣΣΑΛΙΑ					\N	\N	\N
512	\N	\N	\N	ΘΡΑΚΗ	ΘΡΑΚΗ					\N	\N	\N
510	\N	\N	\N	ΚΕΝΤΡΙΚΗ ΜΑΚΕΔΟΝΙΑ  	Κ-ΜΑΚΕΔ 					\N	\N	\N
513	\N	\N	\N	ΚΡΗΤΗ               	ΚΡΗΤΗ   					\N	\N	\N
514	\N	\N	\N	ΝΗΣΟΙ ΑΙΓΑΙΟΥ       	Ν-ΑΙΓΑΙΟ					\N	\N	\N
\.


--
-- Data for Name: hcore_politicaldivision; Type: TABLE DATA; Schema: public; Owner: hydroscope
--

COPY hcore_politicaldivision (garea_ptr_id, parent_id, code) FROM stdin;
1	\N	AF
2	\N	AX
3	\N	AL
4	\N	DZ
5	\N	AS
6	\N	AD
7	\N	AO
8	\N	AI
9	\N	AQ
10	\N	AG
11	\N	AR
12	\N	AM
13	\N	AW
14	\N	AU
15	\N	AT
16	\N	AZ
17	\N	BS
18	\N	BH
19	\N	BD
20	\N	BB
21	\N	BY
22	\N	BE
23	\N	BZ
24	\N	BJ
25	\N	BM
26	\N	BT
27	\N	BO
28	\N	BA
29	\N	BW
30	\N	BV
31	\N	BR
32	\N	IO
33	\N	BN
34	\N	BG
35	\N	BF
36	\N	BI
37	\N	KH
38	\N	CM
39	\N	CA
40	\N	CV
41	\N	KY
42	\N	CF
43	\N	TD
44	\N	CL
45	\N	CN
46	\N	CX
47	\N	CC
48	\N	CO
49	\N	KM
50	\N	CG
51	\N	CD
52	\N	CK
53	\N	CR
54	\N	CI
55	\N	HR
56	\N	CU
57	\N	CY
58	\N	CZ
59	\N	DK
60	\N	DJ
61	\N	DM
62	\N	DO
63	\N	EC
64	\N	EG
65	\N	SV
66	\N	GQ
67	\N	ER
68	\N	EE
69	\N	ET
70	\N	FK
71	\N	FO
72	\N	FJ
73	\N	FI
74	\N	FR
75	\N	GF
76	\N	PF
77	\N	TF
78	\N	GA
79	\N	GM
80	\N	GE
81	\N	DE
82	\N	GH
83	\N	GI
84	\N	GR
85	\N	GL
86	\N	GD
87	\N	GP
88	\N	GU
89	\N	GT
90	\N	GG
91	\N	GN
92	\N	GW
93	\N	GY
94	\N	HT
95	\N	HM
96	\N	VA
97	\N	HN
98	\N	HK
99	\N	HU
100	\N	IS
101	\N	IN
102	\N	ID
103	\N	IR
104	\N	IQ
105	\N	IE
106	\N	IM
107	\N	IL
108	\N	IT
109	\N	JM
110	\N	JP
111	\N	JE
112	\N	JO
113	\N	KZ
114	\N	KE
115	\N	KI
116	\N	KP
117	\N	KR
118	\N	KW
119	\N	KG
120	\N	LA
121	\N	LV
122	\N	LB
123	\N	LS
124	\N	LR
125	\N	LY
126	\N	LI
127	\N	LT
128	\N	LU
129	\N	MO
130	\N	MK
131	\N	MG
132	\N	MW
133	\N	MY
134	\N	MV
135	\N	ML
136	\N	MT
137	\N	MH
138	\N	MQ
139	\N	MR
140	\N	MU
141	\N	YT
142	\N	MX
143	\N	FM
144	\N	MD
145	\N	MC
146	\N	MN
147	\N	ME
148	\N	MS
149	\N	MA
150	\N	MZ
151	\N	MM
152	\N	NA
153	\N	NR
154	\N	NP
155	\N	NL
156	\N	AN
157	\N	NC
158	\N	NZ
159	\N	NI
160	\N	NE
161	\N	NG
162	\N	NU
163	\N	NF
164	\N	MP
165	\N	NO
166	\N	OM
167	\N	PK
168	\N	PW
169	\N	PS
170	\N	PA
171	\N	PG
172	\N	PY
173	\N	PE
174	\N	PH
175	\N	PN
176	\N	PL
177	\N	PT
178	\N	PR
179	\N	QA
180	\N	RE
181	\N	RO
182	\N	RU
183	\N	RW
184	\N	BL
185	\N	SH
186	\N	KN
187	\N	LC
188	\N	MF
189	\N	PM
190	\N	VC
191	\N	WS
192	\N	SM
193	\N	ST
194	\N	SA
195	\N	SN
196	\N	RS
197	\N	SC
198	\N	SL
199	\N	SG
200	\N	SK
201	\N	SI
202	\N	SB
203	\N	SO
204	\N	ZA
205	\N	GS
206	\N	ES
207	\N	LK
208	\N	SD
209	\N	SR
210	\N	SJ
211	\N	SZ
212	\N	SE
213	\N	CH
214	\N	SY
215	\N	TW
216	\N	TJ
217	\N	TZ
218	\N	TH
219	\N	TL
220	\N	TG
221	\N	TK
222	\N	TO
223	\N	TT
224	\N	TN
225	\N	TR
226	\N	TM
227	\N	TC
228	\N	TV
229	\N	UG
230	\N	UA
231	\N	AE
232	\N	GB
233	\N	US
234	\N	UM
235	\N	UY
236	\N	UZ
237	\N	VU
238	\N	VE
239	\N	VN
240	\N	VG
241	\N	VI
242	\N	WF
243	\N	EH
244	\N	YE
245	\N	ZM
246	\N	ZW
301	84	
302	84	
303	84	
304	84	
305	84	
306	84	
307	84	
308	84	
309	84	
310	84	
311	84	
312	84	
313	84	
402	304	
403	304	
404	304	
405	304	
406	302	
407	304	
408	301	
409	301	
410	301	
411	301	
412	301	
413	302	
414	302	
415	305	
416	305	
417	305	
418	305	
419	306	
420	306	
421	306	
422	306	
423	307	
424	307	
425	307	
426	307	
427	308	
428	308	
429	308	
430	308	
431	308	
432	308	
434	308	
435	309	
436	309	
437	309	
438	309	
439	309	
440	312	
441	311	
442	311	
443	311	
444	312	
445	313	
446	313	
447	313	
448	313	
449	310	
450	310	
451	310	
452	310	
453	303	
454	303	
455	303	
456	303	
\.


--
-- Data for Name: hcore_waterdivision; Type: TABLE DATA; Schema: public; Owner: hydroscope
--

COPY hcore_waterdivision (garea_ptr_id) FROM stdin;
511
503
507
506
502
509
501
504
505
508
512
510
513
514
\.

